/**
 * http.ts — the guard, the validators and the JSON envelope every handler shares.
 *
 * These endpoints are PUBLIC URLs. Deployment Protection is the perimeter and there is no
 * auth here by design, but "nobody should find it" is not a reason to accept an unbounded
 * payload or an unvalidated field — the flag and the size caps are the only things standing
 * between a stray request and the store.
 */

/** Every response this API produces is JSON. See `assertJson` on the client for why. */
export function json(body: unknown, status = 200, headers: Record<string, string> = {}): Response {
  return new Response(`${JSON.stringify(body)}\n`, {
    status,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      // Never cache an API response at the CDN: a reviewer polling for someone else's remark
      // would be served their own last answer.
      'cache-control': 'no-store',
      ...headers,
    },
  })
}

export const fail = (status: number, error: string, extra: Record<string, unknown> = {}) =>
  json({ error, ...extra }, status)

/**
 * The server-side flag. Deliberately NOT prefixed `VITE_`, so it cannot be inlined into the
 * client bundle even by accident — that prefix is the only thing Vite exposes.
 *
 * A build with the tools disabled must not have reachable endpoints, so this is checked
 * first in every handler, before parsing, before touching the store.
 */
export const apiEnabled = () => process.env.REVIEW_API === 'true'

/** 404, not 403: a disabled endpoint should be indistinguishable from one that isn't there. */
export const disabled = () => fail(404, 'not found')

/** Bodies are small records. 64kB is ~30x the largest legitimate one. */
const MAX_BODY = 64 * 1024

export async function readJson(request: Request): Promise<Record<string, unknown>> {
  const len = Number(request.headers.get('content-length') ?? 0)
  if (len > MAX_BODY) throw new BadRequest('payload too large')
  const text = await request.text()
  if (text.length > MAX_BODY) throw new BadRequest('payload too large')
  try {
    const parsed: unknown = JSON.parse(text || '{}')
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new BadRequest('body must be a JSON object')
    return parsed as Record<string, unknown>
  } catch (err) {
    if (err instanceof BadRequest) throw err
    throw new BadRequest('body is not valid JSON')
  }
}

export class BadRequest extends Error {
  constructor(message: string) { super(message); this.name = 'BadRequest' }
}

/** A required string, trimmed, length-capped. Throws rather than coercing. */
export function str(body: Record<string, unknown>, field: string, max: number): string {
  const v = body[field]
  if (typeof v !== 'string') throw new BadRequest(`${field} must be a string`)
  const t = v.trim()
  if (!t) throw new BadRequest(`${field} must not be empty`)
  if (t.length > max) throw new BadRequest(`${field} must be at most ${max} characters`)
  return t
}

/** An optional string. Empty and missing both become undefined. */
export function optStr(body: Record<string, unknown>, field: string, max: number): string | undefined {
  const v = body[field]
  if (v === undefined || v === null || v === '') return undefined
  if (typeof v !== 'string') throw new BadRequest(`${field} must be a string`)
  const t = v.trim()
  if (t.length > max) throw new BadRequest(`${field} must be at most ${max} characters`)
  return t || undefined
}

export function oneOf<T extends string>(body: Record<string, unknown>, field: string, allowed: readonly T[]): T {
  const v = body[field]
  if (typeof v !== 'string' || !allowed.includes(v as T)) {
    throw new BadRequest(`${field} must be one of ${allowed.join(', ')}`)
  }
  return v as T
}

/**
 * Ids and revision ids become PATHNAMES, so they are restricted to characters that cannot
 * traverse or collide: no slashes, no dots, no percent-encoding. A record id is generated by
 * us, so anything outside this set is a malformed or hostile request, not a user's data.
 */
const SAFE_ID = /^[A-Za-z0-9_-]{1,64}$/
export function safeId(value: string, what = 'id'): string {
  if (!SAFE_ID.test(value)) throw new BadRequest(`${what} must match [A-Za-z0-9_-]{1,64}`)
  return value
}

/** The path segment after `base`, decoded once. `/api/remarks/abc` with base `remarks` -> `abc`. */
export function segmentAfter(request: Request, base: string): string | null {
  const { pathname } = new URL(request.url)
  const parts = pathname.split('/').filter(Boolean)          // ['api','remarks','abc']
  const i = parts.indexOf(base)
  if (i < 0 || i + 1 >= parts.length) return null
  try {
    return decodeURIComponent(parts.slice(i + 1).join('/'))
  } catch {
    return null
  }
}

/**
 * Wraps a handler so a thrown error becomes a JSON error response rather than a runtime
 * stack the platform renders as HTML. An HTML error page reaching the client is exactly the
 * failure `assertJson` exists to catch, and there is no reason to generate one ourselves.
 */
export function handler(fn: (request: Request) => Promise<Response>): (request: Request) => Promise<Response> {
  return async (request) => {
    if (!apiEnabled()) return disabled()
    try {
      return await fn(request)
    } catch (err) {
      if (err instanceof BadRequest) return fail(400, err.message)
      console.error('[api]', err)
      return fail(500, 'internal error')
    }
  }
}

export function newId(): string {
  try {
    if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
      return crypto.randomUUID().replace(/-/g, '')
    }
  } catch { /* fall through */ }
  return `r${Date.now().toString(36)}${Math.random().toString(36).slice(2, 10)}`
}

/**
 * The `fetch` Web Standard export, built from the method handlers a route already declares.
 *
 * ── WHY BOTH SHAPES ──────────────────────────────────────────────────────────────────
 *
 * Vercel's Node.js runtime documents two ways to write a function in `/api` for a project
 * with no framework: `export default { fetch(request) {…} }`, and named method exports
 * (`export function GET(request) {…}`). These routes carried only the second, written as
 * `export const GET = handler(…)` — a const binding rather than the function declaration the
 * documentation shows.
 *
 * Every deployed route answered `500 FUNCTION_INVOCATION_FAILED`, which Vercel defines as an
 * uncaught exception, served as `text/plain`. It is not this code: the same module, bundled
 * the same way and invoked locally, answers JSON on every path — 404 while `REVIEW_API` is
 * unset, 500 with a JSON body when the store is missing, because `handler()` catches
 * everything. A throw before the handler runs is a throw in the platform's invocation of it.
 *
 * So a route now exports BOTH: the named methods, and a default `{ fetch }` that dispatches
 * to them. That is not belt-and-braces for its own sake — the shapes cannot disagree, because
 * the default is built FROM the named exports rather than written a second time beside them.
 * `api/_lib/routes.test.ts` calls both and asserts they answer identically.
 *
 * 405 is answered here rather than falling through, so an unsupported method gets JSON with a
 * reason instead of whatever the platform would have produced.
 */
export function route(methods: Record<string, (request: Request) => Promise<Response>>): {
  fetch: (request: Request) => Promise<Response>
} {
  return {
    async fetch(request: Request): Promise<Response> {
      const fn = methods[request.method.toUpperCase()]
      if (!fn) {
        return fail(405, `${request.method} is not allowed on this endpoint`, {
          allowed: Object.keys(methods).sort(),
        })
      }
      return fn(request)
    },
  }
}
